# Generated by Django 5.0.6 on 2025-11-21 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='portafolio',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='accion',
            field=models.ForeignKey(db_column='id_accion', on_delete=django.db.models.deletion.CASCADE, to='core.accion'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AlterModelTable(
            name='accion',
            table='acciones',
        ),
        migrations.AlterModelTable(
            name='portafolio',
            table='portafolio',
        ),
        migrations.AlterModelTable(
            name='transaccion',
            table='transacciones',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
