# Generated by Django 5.2.7 on 2025-11-22 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_accion_options_alter_portafolio_options_and_more'),
    ]

    operations = [
    ]
